name: autofix.ci

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Update Vite+ configs
        run: vp config
      - name: Apply fixes
        run: vp check --fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'refactor: apply automatic fixes'
