name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  benchmarks:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for OIDC authentication with CodSpeed
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          run-install: false
      - run: bun install --frozen-lockfile
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: vp test bench
          mode: 'simulation'
