on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - name: Checkout Git repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7
      - name: Setup Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Lint, test, and build
        run: vp check && vp test && vp pack
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to npm
        run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
